version: '3.4'

x-environment:
    &common-environment-variables
    DEBUG: 'true'
    PSQL_DSN: postgresql+psycopg2://smallcase_read_write:smallcaseTracker2021@postgresql/smallcase_tracker

services:
    postgresql:
        image: postgres:10.11
        container_name: postgresql
        hostname: postgresql
        environment:
            - POSTGRES_DB=smallcase_tracker
            - POSTGRES_USER=smallcase_read_write
            - POSTGRES_PASSWORD=smallcaseTracker2021
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    portfolio-tracker:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - "postgresql"
        hostname: portfolio-tracker
        container_name: portfolio-tracker
        ports:
            - "8000:80"
        image: portfolio-tracker:latest
        volumes:
            - .:/srv/portfolio-tracker
        stdin_open: true
        tty: true
        environment:
            <<: *common-environment-variables
