"""Added new column in securities

Revision ID: 4ff50dd1ef71
Revises: e1a291b1940d
Create Date: 2021-07-07 18:19:38.864131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff50dd1ef71'
down_revision = 'e1a291b1940d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('securities', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_securities_updated_on'), 'securities', ['updated_on'], unique=False)
    op.drop_index('ix_securities_created_on', table_name='securities')
    op.create_foreign_key(None, 'securities', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'securities', type_='foreignkey')
    op.create_index('ix_securities_created_on', 'securities', ['created_on'], unique=False)
    op.drop_index(op.f('ix_securities_updated_on'), table_name='securities')
    op.drop_column('securities', 'updated_on')
    op.drop_column('securities', 'updated_by')
    # ### end Alembic commands ###
