"""Added new column in transaction

Revision ID: d10a16faea20
Revises: 4ff50dd1ef71
Create Date: 2021-07-12 09:05:52.934188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10a16faea20'
down_revision = '4ff50dd1ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_quantity')
    # ### end Alembic commands ###
